JokesSquad/Models/ErrorViewModel.cs
namespace JokesSquad.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JokesSquad/Models/Jokes.cs
namespace JokesSquad.Models
{
    public class Jokes
    {
        public int id { get; set; }
        public string JokesQuestion { get; set; }
        public string JokesAnswer { get; set; }

        public Jokes()
        {
            
        }
    }
}

JokesSquad/Controllers/HomeController.cs
using JokesSquad.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JokesSquad.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JokesSquad/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JokesSquad.Data;
using JokesSquad.Models;
using Microsoft.AspNetCore.Authorization;

namespace JokesSquad.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Jokes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Jokes.ToListAsync());
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes
                .FirstOrDefaultAsync(m => m.id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        [Authorize]
        // GET: Jokes/Create
        public IActionResult Create()
        {
            return View();
        }
        // GET: Jokes/show search form
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        // POST: Jokes/show search results
        public async Task<IActionResult> ShowSearchResult(String SearchPhrase)
        {
            return View("index", await _context.Jokes.Where(J=>J.JokesQuestion.Contains(SearchPhrase)).ToListAsync());
        }

        /*    public String ShowSearchResult(String SearchPhrase)
            {
                return "Your looking for " + SearchPhrase;
            }*/


        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        //****************important******
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,JokesQuestion,JokesAnswer")] Jokes jokes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jokes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        //****************important******
        [Authorize]

        // GET: Jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes.FindAsync(id);
            if (jokes == null)
            {
                return NotFound();
            }
            return View(jokes);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        //****************important******
        [Authorize]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,JokesQuestion,JokesAnswer")] Jokes jokes)
        {
            if (id != jokes.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jokes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokesExists(jokes.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

     
        // GET: Jokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes
                .FirstOrDefaultAsync(m => m.id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // POST: Jokes/Delete/5
        //****************important******
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jokes = await _context.Jokes.FindAsync(id);
            if (jokes != null)
            {
                _context.Jokes.Remove(jokes);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokesExists(int id)
        {
            return _context.Jokes.Any(e => e.id == id);
        }
    }
}

JokesSquad/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
  
    <link rel="stylesheet" type="text/css" href="css/homeStyle.css">
</head>

<div class="arrow arrow--top">
    <svg xmlns="http://www.w3.org/2000/svg" width="270.11" height="649.9" overflow="visible">
        <style>
            .geo-arrow {
                fill: none;
                stroke: #fff;
                stroke-width: 2;
                stroke-miterlimit: 10
            }
        </style>
        <g class="item-to bounce-1">
            <path class="geo-arrow draw-in" d="M135.06 142.564L267.995 275.5 135.06 408.434 2.125 275.499z" />
        </g>
        <circle class="geo-arrow item-to bounce-2" cx="194.65" cy="69.54" r="7.96" />
        <circle class="geo-arrow draw-in" cx="194.65" cy="39.5" r="7.96" />
        <circle class="geo-arrow item-to bounce-3" cx="194.65" cy="9.46" r="7.96" />
        <g class="geo-arrow item-to bounce-2">
            <path class="st0 draw-in" d="M181.21 619.5l13.27 27 13.27-27zM194.48 644.5v-552" />
        </g>
    </svg>
</div>
<div class="arrow arrow--bottom">
    <svg xmlns="http://www.w3.org/2000/svg" width="31.35" height="649.9" overflow="visible">
        <style>
            .geo-arrow {
                fill: none;
                stroke: #fff;
                stroke-width: 2;
                stroke-miterlimit: 10
            }
        </style>
        <g class="item-to bounce-1">
            <circle class="geo-arrow item-to bounce-3" cx="15.5" cy="580.36" r="7.96" />
            <circle class="geo-arrow draw-in" cx="15.5" cy="610.4" r="7.96" />
            <circle class="geo-arrow item-to bounce-2" cx="15.5" cy="640.44" r="7.96" />
            <g class="item-to bounce-2">
                <path class="geo-arrow draw-in" d="M28.94 30.4l-13.26-27-13.27 27zM15.68 5.4v552" />
            </g>
        </g>
    </svg>
</div>
<div class="main">
    <div class="main__text-wrapper">
        <h1 class="main__title">Jokes meme Page</h1>
        <h2>Publish your jokes here</h2>
        <svg xmlns="http://www.w3.org/2000/svg" class="dotted-circle" width="352" height="352" overflow="visible">
            <circle cx="176" cy="176" r="174" fill="none" stroke="#fff" stroke-width="2" stroke-miterlimit="10" stroke-dasharray="12.921,11.9271" />
        </svg>
    </div>
</div>

JokesSquad/Views/Jokes/Create.cshtml
@model JokesSquad.Models.Jokes

@{
    ViewData["Title"] = "Create";
}


<h1>Create</h1>

<h4>Jokes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JokesQuestion" class="control-label"></label>
                <input asp-for="JokesQuestion" class="form-control" />
                <span asp-validation-for="JokesQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokesAnswer" class="control-label"></label>
                <input asp-for="JokesAnswer" class="form-control" />
                <span asp-validation-for="JokesAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesSquad/Views/Jokes/Delete.cshtml
@model JokesSquad.Models.Jokes

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jokes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokesQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokesQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokesAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokesAnswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JokesSquad/Views/Jokes/Details.cshtml
@model JokesSquad.Models.Jokes

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Jokes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokesQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokesQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokesAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokesAnswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JokesSquad/Views/Jokes/Edit.cshtml
@model JokesSquad.Models.Jokes

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Jokes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="JokesQuestion" class="control-label"></label>
                <input asp-for="JokesQuestion" class="form-control" />
                <span asp-validation-for="JokesQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokesAnswer" class="control-label"></label>
                <input asp-for="JokesAnswer" class="form-control" />
                <span asp-validation-for="JokesAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesSquad/Views/Jokes/Index.cshtml
@model IEnumerable<JokesSquad.Models.Jokes>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JokesQuestion)
            </th>
           @*  <th>
                @Html.DisplayNameFor(model => model.JokesAnswer)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JokesQuestion)
            </td>
           @*  <td>
                @Html.DisplayFor(modelItem => item.JokesAnswer)
            </td> *@
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

JokesSquad/Views/Jokes/ShowSearchForm.cshtml
<h4>Search for a Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResult">
           
            <div class="form-group">
                <label for ="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
               
            </div>
            <div class="seach_btn">
                <button class="button-36" role="button">Search</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

JokesSquad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JokesSquad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JokesSquad.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JokesSquad</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
           
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Jokes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="ShowSearchForm">Search</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - JokesSquad - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>